name: Release package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Semantic Release
        uses: AlphaMycelium/psr-action@master
        with:
          pypi_username: jesdi
          pypi_password: ${{ secrets.pypi_password }}
          github_token: ${{ secrets.GITHUB_TOKEN }}